/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vergel;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vicente
 */
public class JF_Empleados extends javax.swing.JFrame {

    JF_Admin jf_admin;

    private Connection conexion;
    private Statement st;
    private ResultSet rs;

    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Vergel", "root", "ninoinkieto1");
            st = conexion.createStatement();

            rs = st.executeQuery("Select * from Empleado");

            rs.next();

            this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_apellidos.setText(rs.getString("Apellidos"));
            this.jtf_edad.setText(rs.getString("Edad"));
            this.jtf_genero.setText(rs.getString("Genero"));
            this.jtf_direccion.setText(rs.getString("Direccion"));
            this.jtf_cargo.setText(rs.getString("Cargo"));

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    /**
     * Creates new form JF_Empleados
     */
    public JF_Empleados() {
        initComponents();
        Conectar();
        tabla();
    }

    public JF_Empleados(JF_Admin jf_admin) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jf_admin = jf_admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_empleadoid = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellidos = new javax.swing.JLabel();
        jl_edad = new javax.swing.JLabel();
        jl_genero = new javax.swing.JLabel();
        jl_cargo = new javax.swing.JLabel();
        jl_direccion = new javax.swing.JLabel();
        jtf_empleadoid = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellidos = new javax.swing.JTextField();
        jtf_edad = new javax.swing.JTextField();
        jtf_genero = new javax.swing.JTextField();
        jtf_cargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empleados = new javax.swing.JTable();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jtf_direccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_filtro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jl_empleados = new javax.swing.JLabel();
        jb_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jl_empleadoid.setText("EmpleadoID");

        jl_nombre.setText("Nombre");

        jl_apellidos.setText("Apellidos");

        jl_edad.setText("Edad");

        jl_genero.setText("Genero");

        jl_cargo.setText("Cargo");

        jl_direccion.setText("Direccion");

        jtf_empleadoid.setEditable(false);
        jtf_empleadoid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtf_apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_edad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_genero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_cargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jt_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_empleados);

        jb_primero.setText("|<");
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });

        jb_anterior.setText("<<");
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });

        jb_siguiente.setText(">>");
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });

        jb_ultimo.setText(">|");
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jtf_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Buscar:");

        jtf_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_filtroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_empleadoid)
                                    .addComponent(jl_nombre)
                                    .addComponent(jl_apellidos)
                                    .addComponent(jl_edad))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_nombre)
                                    .addComponent(jtf_empleadoid)
                                    .addComponent(jtf_edad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_genero)
                                    .addComponent(jl_direccion)
                                    .addComponent(jl_cargo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jb_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jb_guardar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jb_modificar)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jb_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_empleadoid)
                                    .addComponent(jtf_empleadoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_nombre)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_apellidos)
                                    .addComponent(jtf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 83, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_edad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_genero)
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_direccion)
                            .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_cargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb_modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.Color.cyan);

        jl_empleados.setFont(new java.awt.Font("Abyssinica SIL", 3, 24)); // NOI18N
        jl_empleados.setText("Empleados");

        jb_regresar.setText("Regresar");
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_empleados)
                .addGap(201, 201, 201)
                .addComponent(jb_regresar)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_empleados)
                    .addComponent(jb_regresar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        jf_admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jtf_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_filtroKeyPressed
        // TODO add your handling code here:
        try {
            String filtro = jtf_filtro.getText();
            String sql = "select * from Empleado where Nombre like " + "'" + "%" + filtro + "%" + "'";
            rs = st.executeQuery("select * from Empleado where Nombre like " + "'" + "%" + filtro + "%" + "'");
            //System.out.print(sql);
            jt_empleados.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "error Eres puto" + e);
        }
    }//GEN-LAST:event_jtf_filtroKeyPressed

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked

        jtf_empleadoid.setText("");
        jtf_nombre.setText("");
        jtf_apellidos.setText("");
        jtf_edad.setText("");
        jtf_genero.setText("");
        jtf_direccion.setText("");
        jtf_cargo.setText("");


    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        try {
            st.executeUpdate("delete from Empleado where EmpleadoID=" + this.jtf_empleadoid.getText());
            rs = st.executeQuery("select * from Empleado");
            rs.first();

            this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_apellidos.setText(rs.getString("Apellidos"));
            this.jtf_edad.setText(rs.getString("Edad"));
            this.jtf_genero.setText(rs.getString("Genero"));
            this.jtf_direccion.setText(rs.getString("Direccion"));
            this.jtf_cargo.setText(rs.getString("Cargo"));

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        // TODO add your handling code here:
        try {
            String empleado = this.jtf_empleadoid.getText();
            String nombre = this.jtf_nombre.getText();
            String apellidos = this.jtf_apellidos.getText();
            String edad = this.jtf_edad.getText();
            String genero = this.jtf_genero.getText();
            String direccion = this.jtf_direccion.getText();
            String cargo = this.jtf_cargo.getText();

            st.executeUpdate("Update Empleado set Nombre='" + nombre + "',Apellidos='" + apellidos + "',Edad='" + edad + "',Genero='" + genero + "',Direccion='" + direccion + "',Cargo='" + cargo + "', where EmpleadoID='" + empleado + "'");
            rs = st.executeQuery("select * from Empleado");
            rs.first();

            this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_apellidos.setText(rs.getString("Apellidos"));
            this.jtf_edad.setText(rs.getString("Edad"));
            this.jtf_genero.setText(rs.getString("Genero"));
            this.jtf_direccion.setText(rs.getString("Direccion"));
            this.jtf_cargo.setText(rs.getString("Cargo"));
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = this.jtf_nombre.getText();
            String apellidos = this.jtf_apellidos.getText();
            String edad = this.jtf_edad.getText();
            String genero = this.jtf_genero.getText();
            String direccion = this.jtf_direccion.getText();
            String cargo = this.jtf_cargo.getText();

            st.executeUpdate("Insert into Empleado (Nombre,Apellidos,Edad,Genero,Direccion,Cargo)" + " values ('" + nombre + "','" + apellidos + "','" + edad + "','" + genero + "','" + direccion + "','" + cargo + "');");
            rs = st.executeQuery("select * from Empleado");
            rs.first();

            this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_apellidos.setText(rs.getString("Apellidos"));
            this.jtf_edad.setText(rs.getString("Edad"));
            this.jtf_genero.setText(rs.getString("Genero"));
            this.jtf_direccion.setText(rs.getString("Direccion"));
            this.jtf_cargo.setText(rs.getString("Cargo"));
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        // TODO add your handling code here:
        jtf_empleadoid.setText("");
        jtf_nombre.setText("");
        jtf_apellidos.setText("");
        jtf_edad.setText("");
        jtf_genero.setText("");
        jtf_direccion.setText("");
        jtf_cargo.setText("");
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isLast() == false) {
                rs.last();
                this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
                this.jtf_nombre.setText(rs.getString("Nombre"));
                this.jtf_apellidos.setText(rs.getString("Apellidos"));
                this.jtf_edad.setText(rs.getString("Edad"));
                this.jtf_genero.setText(rs.getString("Genero"));
                this.jtf_direccion.setText(rs.getString("Direccion"));
                this.jtf_cargo.setText(rs.getString("Cargo"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isLast() == false) {
                rs.next();
                this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
                this.jtf_nombre.setText(rs.getString("Nombre"));
                this.jtf_apellidos.setText(rs.getString("Apellidos"));
                this.jtf_edad.setText(rs.getString("Edad"));
                this.jtf_genero.setText(rs.getString("Genero"));
                this.jtf_direccion.setText(rs.getString("Direccion"));
                this.jtf_cargo.setText(rs.getString("Cargo"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isFirst() == false) {
                rs.previous();
                this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
                this.jtf_nombre.setText(rs.getString("Nombre"));
                this.jtf_apellidos.setText(rs.getString("Apellidos"));
                this.jtf_edad.setText(rs.getString("Edad"));
                this.jtf_genero.setText(rs.getString("Genero"));
                this.jtf_direccion.setText(rs.getString("Direccion"));
                this.jtf_cargo.setText(rs.getString("Cargo"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primeroMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isFirst() == false) {
                rs.first();
                this.jtf_empleadoid.setText(rs.getString("EmpleadoID"));
                this.jtf_nombre.setText(rs.getString("Nombre"));
                this.jtf_apellidos.setText(rs.getString("Apellidos"));
                this.jtf_edad.setText(rs.getString("Edad"));
                this.jtf_genero.setText(rs.getString("Genero"));
                this.jtf_direccion.setText(rs.getString("Direccion"));
                this.jtf_cargo.setText(rs.getString("Cargo"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_primeroMouseClicked

    private void jt_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_empleadosMouseClicked
        // TODO add your handling code here:
        int seleccion = jt_empleados.rowAtPoint(evt.getPoint());
        jtf_empleadoid.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 0)));
        jtf_nombre.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 1)));
        jtf_apellidos.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 2)));
        jtf_edad.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 3)));
        jtf_genero.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 4)));
        jtf_direccion.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 5)));
        jtf_cargo.setText(String.valueOf(jt_empleados.getValueAt(seleccion, 6)));
    }//GEN-LAST:event_jt_empleadosMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        tabla();
        Conectar();
    }//GEN-LAST:event_formComponentShown

    public void tabla() {
        try {
            Conectar();
            rs = st.executeQuery("Select * from Empleado;");
            this.jt_empleados.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JLabel jl_apellidos;
    private javax.swing.JLabel jl_cargo;
    private javax.swing.JLabel jl_direccion;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_empleadoid;
    private javax.swing.JLabel jl_empleados;
    private javax.swing.JLabel jl_genero;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JTable jt_empleados;
    private javax.swing.JTextField jtf_apellidos;
    private javax.swing.JTextField jtf_cargo;
    private javax.swing.JTextField jtf_direccion;
    private javax.swing.JTextField jtf_edad;
    private javax.swing.JTextField jtf_empleadoid;
    private javax.swing.JTextField jtf_filtro;
    private javax.swing.JTextField jtf_genero;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
