/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vergel;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vicente
 */
public class JF_Orden extends javax.swing.JFrame {

    JF_Empleado jf_empleado;
    
    private Connection conexion;     
    private Statement st;     
    private ResultSet rs; 
    
    /**
     * Creates new form JF_Orden
     */
    public void Conectar(){
         try{ 
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/Vergel","root","ninoinkieto1");                     
            st=conexion.createStatement(); 

            rs=st.executeQuery("Select * from Orden");             

            rs.next(); 

            this.jtf_numeroOrden.setText(rs.getString("OrdenID"));                         
            this.jtf_cantidad.setText(rs.getString("Cantidad"));
        }catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        }
    }
    
           
    
    public JF_Orden() {
        initComponents();
        Conectar();
        tabla();
        LlenarComboPlatillo();
        LlenarComboPrecio();
        
    }
    
    public JF_Orden(JF_Empleado jf_empleado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jf_empleado =  jf_empleado;
    }
    
    public void tabla(){
    try{
        Conectar();
        rs=st.executeQuery("Select * from Orden;");
        this.jt_orden.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }
    
    public void LlenarComboPlatillo(){
            try{
                rs = st.executeQuery("Select * from Productos ORDER BY Nombre");
                jcb_producto.removeAllItems();
                
            while(rs.next()){
                jcb_producto.addItem(rs.getString("Nombre")+" - "+rs.getString("Tamano"));
                }
             
        } catch (SQLException ex) {
            Logger.getLogger(JF_Orden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LlenarComboPrecio(){
        try{
                rs = st.executeQuery("Select distinct Precio from Productos ORDER BY Precio");
                jcb_precio.removeAllItems();
                
            while(rs.next()){
                jcb_precio.addItem(rs.getString("Precio"));
                }
             
        } catch (SQLException ex) {
            Logger.getLogger(JF_Orden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_cuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_orden = new javax.swing.JTable();
        jl_numeroOrden = new javax.swing.JLabel();
        jtf_numeroOrden = new javax.swing.JTextField();
        jl_platillo = new javax.swing.JLabel();
        jl_cantidad = new javax.swing.JLabel();
        jb_agregar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_imprimir = new javax.swing.JButton();
        jtf_cantidad = new javax.swing.JTextField();
        jcb_producto = new javax.swing.JComboBox<>();
        jl_precioUnitario = new javax.swing.JLabel();
        jb_regresar = new javax.swing.JButton();
        jl_precioTotal = new javax.swing.JLabel();
        jtf_precioTotal = new javax.swing.JTextField();
        jcb_precio = new javax.swing.JComboBox<>();
        jp_titulo = new javax.swing.JPanel();
        JL_ORDEN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jp_cuerpo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jp_cuerpoComponentShown(evt);
            }
        });

        jt_orden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_orden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ordenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_orden);

        jl_numeroOrden.setText("No. Orden");

        jtf_numeroOrden.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jl_platillo.setText("Platillo");

        jl_cantidad.setText("Cantidad");

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_imprimir.setText("Imprimir");

        jtf_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jcb_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jl_precioUnitario.setText("Precio unitario");

        jb_regresar.setText("Regresar");
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jl_precioTotal.setText("Precio Total");

        jtf_precioTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_precioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_precioTotalActionPerformed(evt);
            }
        });

        jcb_precio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jp_cuerpoLayout = new javax.swing.GroupLayout(jp_cuerpo);
        jp_cuerpo.setLayout(jp_cuerpoLayout);
        jp_cuerpoLayout.setHorizontalGroup(
            jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cuerpoLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                                .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                                        .addComponent(jl_numeroOrden)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                        .addComponent(jtf_numeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                                                .addComponent(jl_cantidad)
                                                .addGap(50, 50, 50))
                                            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                                                .addComponent(jl_precioTotal)
                                                .addGap(32, 32, 32))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                                                .addComponent(jl_precioUnitario)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jtf_precioTotal)
                                            .addComponent(jcb_precio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                                .addComponent(jl_platillo)
                                .addGap(65, 65, 65)
                                .addComponent(jcb_producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81))))
                    .addGroup(jp_cuerpoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                        .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(jp_cuerpoLayout.createSequentialGroup()
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cuerpoLayout.createSequentialGroup()
                        .addComponent(jb_regresar)
                        .addGap(157, 157, 157))))
        );
        jp_cuerpoLayout.setVerticalGroup(
            jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cuerpoLayout.createSequentialGroup()
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(jb_regresar))
                    .addGroup(jp_cuerpoLayout.createSequentialGroup()
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_numeroOrden)
                            .addComponent(jtf_numeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_platillo)
                            .addComponent(jcb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_cantidad))
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_precioUnitario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_precioTotal))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        jp_titulo.setBackground(java.awt.Color.cyan);
        jp_titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JL_ORDEN.setFont(new java.awt.Font("Abyssinica SIL", 3, 24)); // NOI18N
        JL_ORDEN.setText("ORDEN");

        javax.swing.GroupLayout jp_tituloLayout = new javax.swing.GroupLayout(jp_titulo);
        jp_titulo.setLayout(jp_tituloLayout);
        jp_tituloLayout.setHorizontalGroup(
            jp_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_ORDEN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_tituloLayout.setVerticalGroup(
            jp_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tituloLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JL_ORDEN)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        jf_empleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        jtf_cantidad.setText("");
        jtf_numeroOrden.setText("");
        jtf_precioTotal.setText("");
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        jtf_numeroOrden.setText("");
        jtf_cantidad.setText("");
        jtf_numeroOrden.setText("");
        jtf_precioTotal.setText("");
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        try{
            String orden = this.jtf_numeroOrden.getText();
            String platillo1 = "" +jcb_producto.getSelectedItem();
            String cantidad=this.jtf_cantidad.getText();
            String precio = "" +this.jcb_precio.getSelectedItem();
            String precioTotal=this.jtf_precioTotal.getText();
            
            st.executeUpdate("Insert into Orden (OrdenID,Nombre,Cantidad,PrecioUnitario,PrecioTotal)"+" values ('"+orden+"','"+platillo1+"','"+cantidad+"','"+precio+"','"+precioTotal+"');");
            rs = st.executeQuery("select * from Orden");
            System.out.print(evt);
            
            this.jtf_numeroOrden.setText(rs.getString("OrdenID"));
            this.jtf_cantidad.setText(rs.getString("Cantidad"));
            this.jtf_precioTotal.setText(rs.getString("PrecioTotal"));
            
        } catch(SQLException err)         {
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jtf_precioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_precioTotalActionPerformed
        // TODO add your handling code here:
       /* jtf_precioTotal = jtf_precioUnitario * jtf_cantidad;*/
    }//GEN-LAST:event_jtf_precioTotalActionPerformed

    private void jt_ordenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ordenMouseClicked
        /*int seleccion = jt_orden.rowAtPoint(evt.getPoint());
        jtf_numeroOrden.setText(String.valueOf(jt_orden.getValueAt(seleccion, 0)));
        jcb_producto.getSelectedItem(String.valueOf(jt_orden.getValueAt(seleccion, 1)));
        jcb_tamano.getSelectedItem(String.valueOf(jt_orden.getValueAt(seleccion, 2)));
        jtf_cantidad.setText(String.valueOf(jt_orden.getValueAt(seleccion, 3)));
        jtf_precioUnitario.setText(String.valueOf(jt_orden.getValueAt(seleccion, 4)));
        jtf_precioTotal.setText(String.valueOf(jt_orden.getValueAt(seleccion, 5)));*/
    }//GEN-LAST:event_jt_ordenMouseClicked

    private void jp_cuerpoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jp_cuerpoComponentShown
        Conectar();
        tabla();
        LlenarComboPlatillo();
        LlenarComboPrecio();

// TODO add your handling code here:
    }//GEN-LAST:event_jp_cuerpoComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Orden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_ORDEN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_imprimir;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JComboBox<String> jcb_precio;
    private javax.swing.JComboBox<String> jcb_producto;
    private javax.swing.JLabel jl_cantidad;
    private javax.swing.JLabel jl_numeroOrden;
    private javax.swing.JLabel jl_platillo;
    private javax.swing.JLabel jl_precioTotal;
    private javax.swing.JLabel jl_precioUnitario;
    private javax.swing.JPanel jp_cuerpo;
    private javax.swing.JPanel jp_titulo;
    private javax.swing.JTable jt_orden;
    private javax.swing.JTextField jtf_cantidad;
    private javax.swing.JTextField jtf_numeroOrden;
    private javax.swing.JTextField jtf_precioTotal;
    // End of variables declaration//GEN-END:variables
}
