/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vergel;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vicente
 */
public class JF_Productos extends javax.swing.JFrame {

    JF_Admin jf_admin;
    
    private Connection conexion;     
    private Statement st;     
    private ResultSet rs; 
    TableRowSorter trs;
    private TableModel dtm;
    
    public void Conectar(){
         try{ 
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/Vergel","root","ninoinkieto1");                     
            st=conexion.createStatement(); 

            rs=st.executeQuery("Select * from Productos");             

            rs.next(); 

            this.jtf_productoid.setText(rs.getString("ProductoID"));                         
            this.jtf_nombre.setText(rs.getString("Nombre"));             
            this.jtf_tamano.setText(rs.getString("Tamano"));
            this.jtf_precio.setText(rs.getString("Precio")); 

        }catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        } 
    }
     /**
     * Creates new form JF_Productos
     */
    public JF_Productos() {
        initComponents();
        Conectar();
        tabla();
     }
        public JF_Productos(JF_Admin jf_admin) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jf_admin =  jf_admin;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_edad = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jb_ultimo = new javax.swing.JButton();
        jtf_tamano = new javax.swing.JTextField();
        jb_modificar = new javax.swing.JButton();
        jb_inicio = new javax.swing.JButton();
        jtf_precio = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jl_productoid = new javax.swing.JLabel();
        jb_cancelar = new javax.swing.JButton();
        jb_Nuevo = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jl_tamano = new javax.swing.JLabel();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jtf_productoid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_regresar = new javax.swing.JButton();
        jtf_filtro = new javax.swing.JTextField();
        jl_busqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jl_edad.setText("Precio");

        jl_nombre.setText("Nombre");

        jb_ultimo.setText(">|");
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });

        jtf_tamano.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_inicio.setText("|<");
        jb_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inicioMouseClicked(evt);
            }
        });

        jtf_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jl_productoid.setText("ProductoID");

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_Nuevo.setText("Nuevo");
        jb_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_NuevoMouseClicked(evt);
            }
        });

        jb_anterior.setText("<<");
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });

        jb_siguiente.setText(">>");
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jl_tamano.setText("Tamaño");

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_productos);

        jtf_productoid.setEditable(false);
        jtf_productoid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel3.setBackground(java.awt.Color.cyan);
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 3, 24)); // NOI18N
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jb_regresar.setText("Regresar");
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jtf_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_filtroKeyPressed(evt);
            }
        });

        jl_busqueda.setText("Busqueda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_edad)
                                .addGap(100, 100, 100)
                                .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jl_productoid)
                                        .addComponent(jl_nombre))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtf_nombre)
                                        .addComponent(jtf_productoid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jl_tamano)
                                    .addGap(89, 89, 89)
                                    .addComponent(jtf_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_busqueda)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jb_regresar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jb_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jb_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_modificar)
                            .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_productoid)
                            .addComponent(jtf_productoid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_tamano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_edad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_regresar)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_busqueda)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jb_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inicioMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isFirst() == false) {
                rs.first();
                this.jtf_productoid.setText(rs.getString("ProductoID"));                         
                this.jtf_nombre.setText(rs.getString("Nombre"));             
                this.jtf_tamano.setText(rs.getString("Tamano"));
                this.jtf_precio.setText(rs.getString("Precio")); 
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_inicioMouseClicked

    public void tabla(){
    try{
        Conectar();
        rs=st.executeQuery("Select * from Productos;");
        this.jt_productos.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }
    
    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        try {
            if (rs.isFirst() == false) {
                rs.previous();
                this.jtf_productoid.setText(rs.getString("ProductoID"));                         
                this.jtf_nombre.setText(rs.getString("Nombre"));             
                this.jtf_tamano.setText(rs.getString("Tamano"));
                this.jtf_precio.setText(rs.getString("Precio"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
         try {
            if (rs.isLast() == false) {
                rs.next();
                this.jtf_productoid.setText(rs.getString("ProductoID"));                         
                this.jtf_nombre.setText(rs.getString("Nombre"));             
                this.jtf_tamano.setText(rs.getString("Tamano"));
                this.jtf_precio.setText(rs.getString("Precio"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        } 
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        // TODO add your handling code here:
        try {
            if (rs.isLast() == false) {
                rs.last();
                this.jtf_productoid.setText(rs.getString("ProductoID"));                         
                this.jtf_nombre.setText(rs.getString("Nombre"));             
                this.jtf_tamano.setText(rs.getString("Tamano"));
                this.jtf_precio.setText(rs.getString("Precio"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        // TODO add your handling code here:
        try{
            st.executeUpdate("delete from Productos where ProductoID="+this.jtf_productoid.getText());
            rs = st.executeQuery("select * from Productos");
            rs.first();

            this.jtf_productoid.setText(rs.getString("ProductoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_tamano.setText(rs.getString("Tamano"));
            this.jtf_precio.setText(rs.getString("Precio"));

        } catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        // TODO add your handling code here:
        try{
            String producto=this.jtf_productoid.getText();
            String nombre=this.jtf_nombre.getText();
            String tamano=this.jtf_tamano.getText();
            String precio=this.jtf_precio.getText();

            st.executeUpdate("Update Productos set nombre='"+nombre+"',tamano='"+tamano+"',precio='"+precio+"' where productoid='"+producto+"'");
            rs = st.executeQuery("select * from Productos");
            rs.first();

            this.jtf_productoid.setText(rs.getString("ProductoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_tamano.setText(rs.getString("Tamano"));
            this.jtf_precio.setText(rs.getString("Precio"));
        } catch(SQLException err)         {
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        try{
            String nombre=this.jtf_nombre.getText();
            String tamano=this.jtf_tamano.getText();
            String precio=this.jtf_precio.getText();

            st.executeUpdate("Insert into Productos (Nombre,Tamano,Precio)"+" values ('"+nombre+"','"+tamano+"','"+precio+"');");
            rs = st.executeQuery("select * from Productos");
            rs.first();

            this.jtf_productoid.setText(rs.getString("ProductoID"));
            this.jtf_nombre.setText(rs.getString("Nombre"));
            this.jtf_tamano.setText(rs.getString("Tamano"));
            this.jtf_precio.setText(rs.getString("Precio"));
        } catch(SQLException err)         {
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());
        }
        tabla();
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_NuevoMouseClicked
        jtf_productoid.setText("");
        jtf_nombre.setText("");
        jtf_tamano.setText("");
        jtf_precio.setText("");
    }//GEN-LAST:event_jb_NuevoMouseClicked

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        jf_admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        jtf_productoid.setText("");
        jtf_nombre.setText("");
        jtf_tamano.setText("");
        jtf_precio.setText("");
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jt_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_productosMouseClicked
        // TODO add your handling code here:
        int seleccion = jt_productos.rowAtPoint(evt.getPoint());
        jtf_productoid.setText(String.valueOf(jt_productos.getValueAt(seleccion, 0)));
        jtf_nombre.setText(String.valueOf(jt_productos.getValueAt(seleccion, 1)));
        jtf_tamano.setText(String.valueOf(jt_productos.getValueAt(seleccion, 2)));
        jtf_precio.setText(String.valueOf(jt_productos.getValueAt(seleccion, 3)));
    }//GEN-LAST:event_jt_productosMouseClicked

    private void jtf_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_filtroKeyPressed
        // TODO add your handling code here:
        try{
        String filtro = jtf_filtro.getText();
        String sql = "select * from Productos where Nombre like " + "'"+"%"+ filtro+"%"+"'";
        rs = st.executeQuery("select * from Productos where Nombre like " + "'"+"%"+ filtro+"%"+"'");
        //System.out.print(sql);
        jt_productos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(this,"error Eres puto"+ e);
        }            
        
    }//GEN-LAST:event_jtf_filtroKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Conectar();
        tabla();// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_Nuevo;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_inicio;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JLabel jl_busqueda;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_productoid;
    private javax.swing.JLabel jl_tamano;
    private javax.swing.JTable jt_productos;
    private javax.swing.JTextField jtf_filtro;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_precio;
    private javax.swing.JTextField jtf_productoid;
    private javax.swing.JTextField jtf_tamano;
    // End of variables declaration//GEN-END:variables
}
